import {Rubik} from 'next/font/google';
import localFont from 'next/font/local'; 
import "./globals.css";

//components.......
import Navbar from './navbar/page'

const rubik_init = Rubik({
  subsets: ['latin'],
  weight: ["300","500","700","400"],
  variable: '--font-rubik',

})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "$Next Js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${rubik_init.variable} ${rubik_init.variable} antialiased`}>
          <Navbar />
        {children}
      </body>
    </html>
  );
}
